### ISSUE TITLE
TypeError when trying to use tool to create first test

### ISSUE THREAD

**Issue by daqieq** [alteryx/alteryx-tool-generator#54]
I downloaded today:
Latest LTS Version: 10.16.0 (includes npm 6.9.0)

But my first run hit an error:

```
C:\Users\ah57473\Documents\~Alteryx\alteryx-tool-generator-master\app\get-install-location.js:18
    const installDir = (items.find(findInstallDir)).value
                                                    ^

TypeError: Cannot read property 'value' of undefined
    at regKey.values (C:\Users\ah57473\Documents\~Alteryx\alteryx-tool-generator-master\app\get-install-location.js:18:53)
    at ChildProcess.<anonymous> (C:\Users\ah57473\Documents\~Alteryx\alteryx-tool-generator-master\node_modules\winreg\lib\registry.js:492:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```

**Comment by njessee** [comment]
I'm having the same issue

**Comment by goppi0** [comment]
Have the same error. The tool seems to look for a registry key that the later versions of Alteryx don't create anymore. 
I changed line 18 in the get-install-location.js file to the following to fix this issue rather than adding a registry value:
`const installDir = 'C:\\Program Files\\Alteryx\\bin'`
